import { Injectable, signal, PLATFORM_ID, Inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly STORAGE_KEY = 'elms_language';
  
  // Current language signal ('en' or 'gu')
  currentLang = signal<string>('en');

  private translations: any = {
    'en': {
      'DASHBOARD': 'Dashboard',
      'APPLY_LEAVE': 'Apply Leave',
      'STAFF_PORTAL': 'Staff Portal',
      'HOD_APPROVALS': 'HOD Approvals',
      'MY_STATUS': 'My Status',
      'POLICIES': 'Policies',
      'SIGN_OUT': 'Sign Out',
      'WELCOME_BACK': 'Welcome Back',
      'OFFLINE': 'Offline',
      'ONLINE': 'Online',
      'SYSTEM_MANAGER': 'System Manager',
      'OVERVIEW': 'Overview',
      'REQUESTS': 'Requests',
      'SETTINGS': 'Settings',
      'PULL_FROM_CLOUD': 'Pull from Cloud',
      'SYNC_QUEUE': 'Sync Queue',
      'CONTROL_PANEL': 'Control Panel',
      'STAFF_MENU': 'Staff Menu',
      'PROFILE_UPDATE': 'Profile Update',
      'SYNCING': 'Syncing...',
      'ELMS_PORTAL': 'ELMS Portal',
      'ELMS_ADMIN': 'ELMS ADMIN',
      'REQUISITION_WINDOW': 'Session Window',
      'LEAVE_QUOTA': 'Leave Quota Overview',
      'ANALYTICS': 'Analytics',
      'SESSION_ANALYTICS': 'Session Analytics',
      'STATUS_HEALTH': 'Status Health',
      'USAGE_METRICS': 'Usage metrics',
      'TOTAL_REQUESTS': 'Total Requests',
      'APPROVED': 'Approved',
      'PENDING': 'Pending',
      'REJECTED': 'Rejected',
      'ID': 'ID',
      'DEPT': 'Dept',
      'SESSION': 'Session',
      'SESSION_WINDOW': 'Session Window',
      'LEAVE_QUOTA_OVERVIEW': 'Leave Quota Overview',
      'ACCUMULATED_TOTAL': 'Accumulated Total',
      'USED': 'Used',
      'LIMIT': 'Limit',
      'SYSTEM_STATS': 'System Stats',
      'TOTAL_STAFF': 'Total Staff',
      'STAFF_DISTRIBUTION': 'Staff Distribution',
      'HOD_APP': 'HOD Appr.',
      'FINAL_APP': 'Final Appr.',
      'SYSTEM_HEALTH': 'System Health',
      'COMMAND_CENTER': 'Command Center',
      'LEAVE_PORTFOLIO': 'Personal Leave Portfolio',
      'INSTITUTIONAL_INTEL': 'Institutional Intelligence',
      'APP_BREAKDOWN': 'Application Breakdown',
      'DEPT_DISTRO': 'Departmental Distro',
      'ACTIVE_ACADEMIC_CYCLE': 'Active Academic Cycle',
      'QUEUE_HOD': 'Queue (HOD)',
      'ADMIN_QUEUE': 'Admin Queue',
      'DAYS_TAKEN': 'Days Taken',
      'STAFF_COUNT': 'Staff Count',
      'SYSTEM_INTELLIGENCE_REPORT': 'System Intelligence Report',
      'RESET_FILTERS': 'Reset Filters',
      'STAFF_DIRECTORY': 'Staff Directory',
      'LEAVE_HISTORY': 'Leave History',
      'BALANCE_SUMMARY': 'Balance Summary',
      'SEARCH_PLACEHOLDER': 'Search staff, code or type...',
      'DEPT_FILTER_PLACEHOLDER': 'Filter by Dept Code (1-7)',
      'EMPLOYEE_MASTER_BALANCE_SUMMARY': 'Employee Master Balance Summary',
      'SYNC_ALL_TO_DB': 'Sync All to DB',
      'REFRESH_VIEW': 'Refresh View',
      'PRINT_PDF': 'Print PDF',
      'DEPARTMENT_INFO': 'Department Info',
      'ROLE': 'Role',
      'EMAIL': 'Email',
      'STAFF_NAME': 'Staff Name',
      'LEAVE_PERIOD': 'Leave Period',
      'DAYS': 'Days',
      'STATUS': 'Status',
      'ACTIONS': 'Actions',
      'SAVE': 'Save',
      'CANCEL': 'Cancel',
      'EDIT': 'Edit',
      'STAFF_DIRECTORY_TITLE': 'Staff Directory',
      'MANAGE_PERSONNEL': 'Manage personnel.',
      'ADD_NEW_STAFF': 'Add New Staff',
      'EDIT_STAFF_MEMBER': 'Edit Staff Member',
      'EMP_CODE_OPTIONAL': 'Employee Code (Optional - Auto generated if blank)',
      'FULL_NAME': 'Full Name',
      'EMAIL_ADDRESS': 'Email Address',
      'TEACHING': 'Teaching',
      'PEON': 'Peon',
      'MANAGED_DEPTS_HOD': 'Managed Departments (HOD)',
      'MANAGED_DEPTS_INFO': 'Comma-separated dept codes this HOD manages.',
      'SAVE_CHANGES': 'Save Changes',
      'CONFIRM_REGISTRATION': 'Confirm Registration',
      'STAFF_MEMBER': 'Staff Member',
      'ROLE_TYPE': 'Role / Type',
      'NO_STAFF_FOUND': 'No matching staff members found.',
      'HOD_OF': 'HOD of:',
      'SELECT_TYPE': 'Select Type',
      'SYSTEM_CONFIGURATIONS': 'System Configurations',
      'GLOBAL_CONFIG_SUBTITLE': 'Manage Global Academic Sessions & Leave Quota Rules.',
      'ACTIVE': 'Active',
      'SESSION_MANAGEMENT': 'Session Management',
      'SWITCH_SESSION': 'Switch Session',
      'SESSION_NAME': 'Session Name',
      'START_DATE': 'Start Date',
      'END_DATE': 'End Date',
      'APPLY_CHANGES': 'Apply Changes',
      'LOGIC_GUIDE': 'Logic Guide',
      'ACCUMULATING_MODE': 'Accumulating mode',
      'QUOTA_BASED_DEDUCTION': 'Quota-based deduction',
      'UPDATE_POLICY': 'Update Policy',
      'CONFIGURE_RULE': 'Configure Rule',
      'ANNUAL_LIMIT': 'Annual Limit',
      'CARRY_FORWARD_SUPPORT': 'Carry Forward Support',
      'APPLICABLE_DEPTS': 'Applicable Departments',
      'SAVE_RULE_CONFIG': 'Save Rule Configuration',
      'ACTIVE_LEAVE_POLICIES': 'Active Leave Policies',
      'TRACKING_MODE': 'Tracking Mode',
      'LEAVE_CATEGORY': 'Leave Category',
      'STAFF_SEARCH': 'Staff Search',
      'LEAVE_SEARCH': 'Leave Search',
      'NAME_OR_ID': 'Name or ID',
      'LEAVE_TYPE_PLACEHOLDER': 'Leave Type (e.g. SL, CL)',
      'FILTER_BY_DEPT_CODE': 'Filter by Dept Code',
      'ACTION_REQUIRED_ADMIN': 'Action Required: Admin Decision',
      'STAFF_DETAILS': 'Staff Details',
      'REQUEST': 'Request',
      'REASON': 'Reason',
      'ATTACHMENT': 'Attachment',
      'APPROVE_BTN': 'Approve',
      'REJECT_BTN': 'Reject',
      'AWAITING_ACTION': 'Awaiting Action',
      'AWAITING_HOD_APPROVAL': 'Awaiting HOD Approval',
      'PROCESSED_HISTORY': 'Processed History',
      'LEAVE_DETAILS': 'Leave Details',
      'NO_FILE': 'No File',
      'SYNCING_SPINNER': 'Syncing...',
      'VIEW_BTN': 'View',
      'STAFF': 'Staff',
      'HOD': 'HOD',
      'ADMIN': 'Admin',
      'OTHER': 'Other',
      'MANAGED_DEPTS': 'Managed Departments',
      'SCOPE_SESSION': 'Scope: Session-wide',
      'FIND_EMPLOYEE': 'Find Employee',
      'ENTER_EMP_CODE': 'Enter Employee Code (e.g. 101)',
      'SEARCH_EMPLOYEE': 'Search Employee',
      'INFO': 'Info',
      'DAYS_SELECTED': 'Days Selected',
      'STATS': 'Stats',
      'DAYS_TAKEN_ACCUMULATING': 'Days Taken (Accumulating Mode)',
      'DAYS_AVAILABLE_QUOTA': 'Days Available (Quota Mode)',
      'NEW_LEAVE_APP': 'New Leave Application',
      'EDIT_LEAVE_APP': 'Edit Leave Application',
      'EMP_CODE_LABEL': 'Employee Code',
      'DEPT_CODE_LABEL': 'Department Code',
      'SELECT_LEAVE_TYPE': 'Select Leave Type',
      'REASON_FOR_APP': 'Reason for Application',
      'REASON_PLACEHOLDER': 'Enter reason for applying leave',
      'VACATION_WORKING_DATES': '3 Working Dates During Vacation',
      'UPLOAD_DOC': 'Upload Supporting Document',
      'MEDICAL_COMPULSORY': 'Medical Proof Compulsory',
      'OPTIONAL_PROOF': 'Optional Proof',
      'ALLOWED_FILES': 'Allowed: PDF, JPG, PNG. Mandatory for SL > 3 days.',
      'CONFIRM_SUBMIT': 'Confirm and Submit Request',
      'SEARCH_TO_APPLY': 'Search an employee to apply leave',
      'LEAVE_BALANCE_PANEL': 'Leave Balance Panel',
      'ACADEMIC_SESSION': 'Academic Session',
      'TAKEN': 'Taken',
      'ACCUMULATED': 'Accumulated',
      'REMAINING': 'Remaining',
      'TAKEN_HISTORY': 'Taken History',
      'FROM_TO': 'From - To',
      'NO_LEAVES_FOUND': 'No approved leaves found for this session.',
      'REAL_TIME_SUMMARY': 'This summary reflects real-time data for',
      'AUTO_ADJUST_BALANCE': 'Balances are adjusted automatically after each approval.',
      'WAITING_FOR_SEARCH': 'Waiting for Search',
      'TOTAL': 'Total',
      'NA': 'N/A',
      'POLICY_HUB': 'Policy Central',
      'GOVERNANCE': 'Governance',
      'POLICY_MANAGEMENT': 'Policy Management',
      'POLICY_SUBTITLE': 'Create and manage guidelines for staff and HODs.',
      'CREATE_NEW_POLICY': 'Create New Policy',
      'PUBLISHED': 'Published',
      'DRAFTS': 'Drafts',
      'NO_POLICIES_FOUND': 'No Policies Found',
      'START_BY_CREATING_POLICY': 'Start by creating your first company policy.',
      'UNPUBLISH': 'Unpublish',
      'PUBLISH': 'Publish',
      'POLICY_TITLE': 'Policy Title',
      'FULL_POLICY_CONTENT': 'Full Policy Content',
      'WRITE_POLICY_DETAIL': 'Write the full policy detail here... (Supports multi-line)',
      'SHORT_DESCRIPTION': 'Short Description',
      'LEAVE': 'Leave',
      'DOCS': 'Docs',
      'SR_NO': 'Sr. No.',
      'SYSTEM_PORTAL': 'System Portal',
      'MAIN_MENU': 'Main Menu',
      'MANAGEMENT': 'Management',
      'SYSTEM_TASKS': 'System Tasks',
      'ADMINISTRATOR': 'Administrator',
      'DAYS_TEXT': 'Days',
      'RECORDS': 'Records'
    },
    'gu': {
      'DASHBOARD': 'ડેશબોર્ડ',
      'APPLY_LEAVE': 'રજા માટે અરજી',
      'STAFF_PORTAL': 'સ્ટાફ પોર્ટલ',
      'HOD_APPROVALS': 'HOD મંજૂરીઓ',
      'MY_STATUS': 'મારી સ્થિતિ',
      'POLICIES': 'નીતિઓ',
      'SIGN_OUT': 'સાઇન આઉટ',
      'WELCOME_BACK': 'ફરી સ્વાગત છે',
      'OFFLINE': 'ઓફલાઇન',
      'ONLINE': 'ઓનલાઇન',
      'SYSTEM_MANAGER': 'સિસ્ટમ મેનેજર',
      'OVERVIEW': 'ઝાંખી',
      'REQUESTS': 'વિનંતીઓ',
      'SETTINGS': 'સેટિંગ્સ',
      'PULL_FROM_CLOUD': 'ક્લાઉડ લોડ',
      'SYNC_QUEUE': 'સિંક કતાર',
      'CONTROL_PANEL': 'કંટ્રોલ પેનલ',
      'STAFF_MENU': 'સ્ટાફ મેનૂ',
      'PROFILE_UPDATE': 'પ્રોફાઇલ અપડેટ',
      'SYNCING': 'સિંક થઈ રહ્યું છે...',
      'ELMS_PORTAL': 'ELMS પોર્ટલ',
      'ELMS_ADMIN': 'ELMS એડમિન',
      'REQUISITION_WINDOW': 'સત્ર વિન્ડો',
      'LEAVE_QUOTA': 'રજા ક્વોટા ઝાંખી',
      'ANALYTICS': 'એનાલિટિક્સ',
      'SESSION_ANALYTICS': 'સત્ર એનાલિટિક્સ',
      'STATUS_HEALTH': 'સ્થિતિ સ્વાસ્થ્ય',
      'USAGE_METRICS': 'વપરાશ મેટ્રિક્સ',
      'TOTAL_REQUESTS': 'કુલ વિનંતીઓ',
      'APPROVED': 'મંજૂર',
      'PENDING': 'બાકી',
      'REJECTED': 'અસ્વીકાર',
      'ID': 'આઈડી',
      'DEPT': 'વિભાગ',
      'SESSION': 'સત્ર',
      'SESSION_WINDOW': 'સત્ર વિન્ડો',
      'LEAVE_QUOTA_OVERVIEW': 'રજા ક્વોટા ઝાંખી',
      'ACCUMULATED_TOTAL': 'સંચિત કુલ',
      'USED': 'વપરાયેલ',
      'LIMIT': 'મર્યાદા',
      'SYSTEM_STATS': 'સિસ્ટમ આંકડા',
      'TOTAL_STAFF': 'કુલ સ્ટાફ',
      'STAFF_DISTRIBUTION': 'સ્ટાફ વિતરણ',
      'HOD_APP': 'HOD મંજૂર',
      'FINAL_APP': 'અંતિમ મંજૂર',
      'SYSTEM_HEALTH': 'સિસ્ટમ સ્વાસ્થ્ય',
      'COMMAND_CENTER': 'કમાન્ડ સેન્ટર',
      'LEAVE_PORTFOLIO': 'વ્યક્તિગત રજા પોર્ટફોલિયો',
      'INSTITUTIONAL_INTEL': 'સંસ્થાકીય બુદ્ધિક્ષમતા',
      'APP_BREAKDOWN': 'અરજી વિભાજન',
      'DEPT_DISTRO': 'વિભાગીય વિતરણ',
      'ACTIVE_ACADEMIC_CYCLE': 'સક્રિય શૈક્ષણિક સત્ર',
      'QUEUE_HOD': 'કતાર (HOD)',
      'ADMIN_QUEUE': 'એડમિન કતાર',
      'DAYS_TAKEN': 'લીધેલા દિવસો',
      'STAFF_COUNT': 'સ્ટાફ સંખ્યા',
      'SYSTEM_INTELLIGENCE_REPORT': 'સિસ્ટમ ઇન્ટેલિજન્સ રિપોર્ટ',
      'RESET_FILTERS': 'ફિલ્ટર્સ રીસેટ કરો',
      'STAFF_DIRECTORY': 'સ્ટાફ ડિરેક્ટરી',
      'LEAVE_HISTORY': 'રજા ઇતિહાસ',
      'BALANCE_SUMMARY': 'બેલેન્સ સારાંશ',
      'SEARCH_PLACEHOLDER': 'સ્ટાફ, કોડ અથવા પ્રકાર શોધો...',
      'DEPT_FILTER_PLACEHOLDER': 'વિભાગ કોડ દ્વારા ફિલ્ટર કરો (1-7)',
      'EMPLOYEE_MASTER_BALANCE_SUMMARY': 'કર્મચારી માસ્ટર બેલેન્સ સારાંશ',
      'SYNC_ALL_TO_DB': 'બધા DB માં સિંક કરો',
      'REFRESH_VIEW': 'વ્યુ રિફ્રેશ કરો',
      'PRINT_PDF': 'પીડીએફ પ્રિન્ટ કરો',
      'DEPARTMENT_INFO': 'વિભાગની માહિતી',
      'ROLE': 'ભૂમિકા',
      'EMAIL': 'ઇમેઇલ',
      'STAFF_NAME': 'સ્ટાફનું નામ',
      'LEAVE_PERIOD': 'રજાનો સમયગાળો',
      'DAYS': 'દિવસો',
      'STATUS': 'સ્થિતિ',
      'ACTIONS': 'ક્રિયાઓ',
      'SAVE': 'સાચવો',
      'CANCEL': 'રદ કરો',
      'EDIT': 'ફેરફાર કરો',
      'STAFF_DIRECTORY_TITLE': 'સ્ટાફ ડિરેક્ટરી',
      'MANAGE_PERSONNEL': 'કર્મચારીઓનું સંચાલન કરો.',
      'ADD_NEW_STAFF': 'નવો સ્ટાફ ઉમેરો',
      'EDIT_STAFF_MEMBER': 'સ્ટાફ સભ્યમાં ફેરફાર કરો',
      'EMP_CODE_OPTIONAL': 'કર્મચારી કોડ (વૈકલ્પિક - જો ખાલી હોય તો આપમેળે જનરેટ થાય છે)',
      'FULL_NAME': 'પૂરું નામ',
      'EMAIL_ADDRESS': 'ઇમેઇલ સરનામું',
      'TEACHING': 'શિક્ષણ',
      'PEON': 'પટાવાળો',
      'MANAGED_DEPTS_HOD': 'સંચાલિત વિભાગો (HOD)',
      'MANAGED_DEPTS_INFO': 'આ HOD જે વિભાગ કોડ્સનું સંચાલન કરે છે તે અલ્પવિરામથી અલગ કરેલ છે.',
      'SAVE_CHANGES': 'ફેરફારો સાચવો',
      'CONFIRM_REGISTRATION': 'નોંધણીની પુષ્ટિ કરો',
      'STAFF_MEMBER': 'સ્ટાફ સભ્ય',
      'ROLE_TYPE': 'ભૂમિકા / પ્રકાર',
      'NO_STAFF_FOUND': 'કોઈ મેચિંગ સ્ટાફ સભ્યો મળ્યા નથી.',
      'HOD_OF': 'ના એચઓડી:',
      'SELECT_TYPE': 'પ્રકાર પસંદ કરો',
      'SYSTEM_CONFIGURATIONS': 'સિસ્ટમ રૂપરેખાંકનો',
      'GLOBAL_CONFIG_SUBTITLE': 'વૈશ્વિક શૈક્ષણિક સત્રો અને રજા ક્વોટા નિયમોનું સંચાલન કરો.',
      'ACTIVE': 'સક્રિય',
      'SESSION_MANAGEMENT': 'સત્ર સંચાલન',
      'SWITCH_SESSION': 'સત્ર બદલો',
      'SESSION_NAME': 'સત્રનું નામ',
      'START_DATE': 'શરૂઆતની તારીખ',
      'END_DATE': 'અંતની તારીખ',
      'APPLY_CHANGES': 'ફેરફારો લાગુ કરો',
      'LOGIC_GUIDE': 'લોજિક માર્ગદર્શિકા',
      'ACCUMULATING_MODE': 'એકઠું મોડ',
      'QUOTA_BASED_DEDUCTION': 'ક્વોટા-આધારિત બાદબાકી',
      'UPDATE_POLICY': 'નીતિ અપડેટ કરો',
      'CONFIGURE_RULE': 'નિયમ કન્ફિગર કરો',
      'ANNUAL_LIMIT': 'વાર્ષિક મર્યાદા',
      'CARRY_FORWARD_SUPPORT': 'કેરી ફોરવર્ડ સપોર્ટ',
      'APPLICABLE_DEPTS': 'લાગુ વિભાગો',
      'SAVE_RULE_CONFIG': 'નિયમ રૂપરેખાંકન સાચવો',
      'ACTIVE_LEAVE_POLICIES': 'સક્રિય રજા નીતિઓ',
      'TRACKING_MODE': 'ટ્રેકિંગ મોડ',
      'LEAVE_CATEGORY': 'રજા શ્રેણી',
      'STAFF_SEARCH': 'સ્ટાફ સર્ચ',
      'LEAVE_SEARCH': 'રજા સર્ચ',
      'NAME_OR_ID': 'નામ અથવા આઈડી',
      'LEAVE_TYPE_PLACEHOLDER': 'રજા પ્રકાર (દા.ત. SL, CL)',
      'FILTER_BY_DEPT_CODE': 'વિભાગ કોડ દ્વારા ફિલ્ટર કરો',
      'ACTION_REQUIRED_ADMIN': 'ક્રિયા આવશ્યક: એડમિન નિર્ણય',
      'STAFF_DETAILS': 'સ્ટાફની વિગતો',
      'REQUEST': 'વિનંતી',
      'REASON': 'કારણ',
      'ATTACHMENT': 'જોડાણ',
      'APPROVE_BTN': 'મંજૂર કરો',
      'REJECT_BTN': 'નામંજૂર કરો',
      'AWAITING_ACTION': 'નિર્ણય બાકી',
      'AWAITING_HOD_APPROVAL': 'HOD મંજૂરીની રાહ જોવાઈ રહી છે',
      'PROCESSED_HISTORY': 'પ્રોસેસ્ડ ઇતિહાસ',
      'LEAVE_DETAILS': 'રજા વિગતો',
      'NO_FILE': 'કોઈ ફાઇલ નથી',
      'SYNCING_SPINNER': 'સિંક થઈ રહ્યું છે...',
      'VIEW_BTN': 'જુઓ',
      'STAFF': 'સ્ટાફ',
      'HOD': 'એચઓડી',
      'ADMIN': 'એડમિન',
      'OTHER': 'અન્ય',
      'MANAGED_DEPTS': 'સંચાલિત વિભાગો',
      'SCOPE_SESSION': 'વ્યાપ્તિ: આખા સત્ર માટે',
      'FIND_EMPLOYEE': 'કર્મચારી શોધો',
      'ENTER_EMP_CODE': 'કર્મચારી કોડ દાખલ કરો (દા.ત. 101)',
      'SEARCH_EMPLOYEE': 'કર્મચારી શોધો',
      'INFO': 'માહિતી',
      'DAYS_SELECTED': 'પસંદ કરેલ દિવસો',
      'STATS': 'આંકડા',
      'DAYS_TAKEN_ACCUMULATING': 'દિવસો લીધા (એકઠું મોડ)',
      'DAYS_AVAILABLE_QUOTA': 'દિવસો ઉપલબ્ધ (ક્વોટા મોડ)',
      'NEW_LEAVE_APP': 'નવી રજા અરજી',
      'EDIT_LEAVE_APP': 'રજા અરજીમાં ફેરફાર કરો',
      'EMP_CODE_LABEL': 'કર્મચારી કોડ',
      'DEPT_CODE_LABEL': 'વિભાગ કોડ',
      'SELECT_LEAVE_TYPE': 'રજા પ્રકાર પસંદ કરો',
      'REASON_FOR_APP': 'અરજીનું કારણ',
      'REASON_PLACEHOLDER': 'રજા માટે અરજી કરવાનું કારણ દાખલ કરો',
      'VACATION_WORKING_DATES': 'વેકેશન દરમિયાન ૩ કામકાજના દિવસો',
      'UPLOAD_DOC': 'સહાયક દસ્તાવેજ અપલોડ કરો',
      'MEDICAL_COMPULSORY': 'મેડિકલ પ્રૂફ ફરજિયાત',
      'OPTIONAL_PROOF': 'વૈકલ્પિક પુરાવો',
      'ALLOWED_FILES': 'મંજૂર: PDF, JPG, PNG. SL > 3 દિવસ માટે ફરજિયાત.',
      'CONFIRM_SUBMIT': 'પુષ્ટિ કરો અને વિનંતી સબમિટ કરો',
      'SEARCH_TO_APPLY': 'રજા અરજી કરવા માટે કર્મચારી શોધો',
      'LEAVE_BALANCE_PANEL': 'રજા બેલેન્સ પેનલ',
      'ACADEMIC_SESSION': 'શૈક્ષણિક સત્ર',
      'TAKEN': 'લીધેલ',
      'ACCUMULATED': 'એકઠું થયેલ',
      'REMAINING': 'બાકી',
      'TAKEN_HISTORY': 'લીધેલ ઇતિહાસ',
      'FROM_TO': 'ક્યારથી - ક્યાં સુધી',
      'NO_LEAVES_FOUND': 'આ સત્ર માટે કોઈ મંજૂર રજાઓ મળી નથી.',
      'REAL_TIME_SUMMARY': 'આ સારાંશ રીઅલ-ટાઇમ ડેટા દર્શાવે છે',
      'AUTO_ADJUST_BALANCE': 'દરેક મંજૂરી પછી બેલેન્સ આપમેળે ગોઠવાય છે.',
      'WAITING_FOR_SEARCH': 'શોધની રાહ જોઈ રહ્યા છીએ',
      'TOTAL': 'કુલ',
      'NA': 'નથી',
      'POLICY_HUB': 'નીતિ કેન્દ્ર',
      'GOVERNANCE': 'ગવર્નન્સ',
      'POLICY_MANAGEMENT': 'નીતિ સંચાલન',
      'POLICY_SUBTITLE': 'સ્ટાફ અને HOD માટે માર્ગદર્શિકા બનાવો અને તેનું સંચાલન કરો.',
      'CREATE_NEW_POLICY': 'નવી નીતિ બનાવો',
      'PUBLISHED': 'પ્રકાશિત',
      'DRAFTS': 'ડ્રાફ્ટ્સ',
      'NO_POLICIES_FOUND': 'કોઈ નીતિઓ મળી નથી',
      'START_BY_CREATING_POLICY': 'તમારી પ્રથમ કંપની નીતિ બનાવીને શરૂઆત કરો.',
      'UNPUBLISH': 'અપ્રકાશિત કરો',
      'PUBLISH': 'પ્રકાશિત કરો',
      'POLICY_TITLE': 'નીતિનું શીર્ષક',
      'FULL_POLICY_CONTENT': 'સંપૂર્ણ નીતિ વિગતો',
      'WRITE_POLICY_DETAIL': 'અહીં સંપૂર્ણ નીતિ વિગતો લખો... (મલ્ટી-લાઇન સપોર્ટ કરે છે)',
      'SHORT_DESCRIPTION': 'ટૂંકું વર્ણન',
      'LEAVE': 'રજા',
      'DOCS': 'દસ્તાવેજો',
      'SR_NO': 'ક્રમાંક',
      'SYSTEM_PORTAL': 'સિસ્ટમ પોર્ટલ',
      'MAIN_MENU': 'મુખ્ય મેનુ',
      'MANAGEMENT': 'સંચાલન',
      'SYSTEM_TASKS': 'સિસ્ટમ કાર્યો',
      'ADMINISTRATOR': 'એડમિનિસ્ટ્રેટર',
      'DAYS_TEXT': 'દિવસ',
      'RECORDS': 'રેકોર્ડ્સ'
    }
  };

  constructor(@Inject(PLATFORM_ID) private platformId: Object) {
    if (isPlatformBrowser(this.platformId)) {
      const savedLang = localStorage.getItem(this.STORAGE_KEY);
      if (savedLang) {
        this.currentLang.set(savedLang);
      }
    }
  }

  setLanguage(lang: string) {
    this.currentLang.set(lang);
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem(this.STORAGE_KEY, lang);
    }
  }

  translate(key: string): string {
    const lang = this.currentLang();
    return this.translations[lang]?.[key] || this.translations['en']?.[key] || key;
  }
}
